#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


##---Rules---##
bspc rule -a firefox desktop='^2' focus=on
bspc rule -a Write desktop='^3'
bspc rule -a code-oss desktop='^4'
bspc rule -a caprine desktop='^5'
