#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# laptopscreen is eDP-1
$HOME/.config/bspwm/check_for_school_monitor.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
